@startuml

' hide "E" circle
hide circle

' straight arrows
' skinparam linetype ortho

entity Director {
  id: string
  --

  first_name: string
  last_name: string
  phone_number: number
  email: string
  position: string

  createdAt: date
  deletedAt?: date
}


entity Supplier {
  id: string
  --

  first_name: string
  last_name: string
  phone_number: number
  email: string
  products: [string]
  director_id: Director

  createdAt: date
  deletedAt?: date
}


entity Cook {
  id: string
  --

  name: string
  phone_number: number
  preferred_cuisine: string
  visited_restaurants: string
  director_id: Director

  createdAt: date
  deletedAt?: date
}


entity Visitor {
  id: string
  --

  name: string

  createdAt: date
  deletedAt?: date
}

@enduml